spring.application.name=freelancer-backend

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://dpg-daof8g6k1f9s73brlmg0-a:5432/lakshu_db
spring.datasource.username=lakshu_db_user
spring.datasource.password=QseHU2njx04wqo13QisVe37REVhjV8TN

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=${PORT:8080}
server.address=0.0.0.0

# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lakshanakumaravelan@gmail.com
spring.mail.password=hult qyzp okfy upuh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true